name: Build+Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate index
        run: python3 generate-pages.py
      - name: Build
        uses: Tyler887/jekyllbuild@1.3
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: _site
          branch: deploy
